# Generated by Django 3.1.5 on 2021-02-02 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Abode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('street_address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=20)),
                ('stat', models.CharField(max_length=2)),
                ('zip_code', models.CharField(max_length=5)),
                ('bedrooms', models.IntegerField()),
                ('bathrooms', models.IntegerField()),
                ('SqFoot', models.IntegerField()),
                ('image', models.ImageField(upload_to='humbleabode/images/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
