# Generated by Django 3.1.5 on 2021-02-03 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adobes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abode',
            name='is_sold',
            field=models.BooleanField(null=True),
        ),
    ]
