# Generated by Django 3.1.5 on 2021-02-25 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adobes', '0002_auto_20210224_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abode',
            name='image',
            field=models.ImageField(blank=True, upload_to='humbleabode/images/'),
        ),
    ]
