# Generated by Django 3.1.5 on 2021-02-03 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adobes', '0002_auto_20210202_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abode',
            name='is_sold',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
