# Generated by Django 3.1.5 on 2021-02-02 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adobes', '0002_auto_20210201_1632'),
    ]

    operations = [
        migrations.RenameField(
            model_name='abode',
            old_name='stat',
            new_name='state',
        ),
    ]
