# Generated by Django 3.1.5 on 2021-02-18 03:36

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adobes', '0003_auto_20210202_2044'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=2)),
                ('zip_code', models.CharField(max_length=5)),
            ],
        ),
        migrations.RemoveField(
            model_name='abode',
            name='city',
        ),
        migrations.RemoveField(
            model_name='abode',
            name='state',
        ),
        migrations.RemoveField(
            model_name='abode',
            name='street_address',
        ),
        migrations.RemoveField(
            model_name='abode',
            name='zip_code',
        ),
        migrations.AlterField(
            model_name='abode',
            name='SqFoot',
            field=models.PositiveIntegerField(default=100, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Square Feet:'),
        ),
        migrations.AlterField(
            model_name='abode',
            name='bathrooms',
            field=models.DecimalField(decimal_places=1, max_digits=3, validators=[django.core.validators.MinValueValidator(Decimal('0.5'))], verbose_name='Bathrooms:'),
        ),
        migrations.AlterField(
            model_name='abode',
            name='bedrooms',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Bedrooms:'),
        ),
        migrations.AlterField(
            model_name='abode',
            name='image',
            field=models.ImageField(blank=True, default='adobes\\static\\default.png', upload_to='humbleabode/images/'),
        ),
    ]
