# Generated by Django 3.1.5 on 2021-02-02 03:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adobes', '0003_auto_20210201_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abode',
            name='SqFoot',
            field=models.PositiveIntegerField(default=100, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='abode',
            name='bathrooms',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
        migrations.AlterField(
            model_name='abode',
            name='bedrooms',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
