# Generated by Django 3.1.5 on 2021-02-02 03:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adobes', '0004_auto_20210201_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abode',
            name='bathrooms',
            field=models.DecimalField(decimal_places=1, max_digits=3, validators=[django.core.validators.MinValueValidator(0.5)]),
        ),
    ]
