# Generated by Django 3.1.5 on 2021-02-02 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adobes', '0005_auto_20210201_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abode',
            name='price',
            field=models.PositiveIntegerField(),
        ),
    ]
